export type MeterInfo = { meter_type: string; units: string };

export const DEFAULT_DEVICE_METERS: Record<string, MeterInfo> = {
  'SMS-II-001': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-002': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-003': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-004': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-005': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-006': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-007': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-008': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-009': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-010': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-011': { meter_type: 'EVC', units: 'CM' },
  'SMS-II-012': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-013': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-014': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-015': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-016': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-017': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-018': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-019': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-020': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-021': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-022': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-023': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-024': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-025': { meter_type: 'EVC', units: 'CM' },
  'SMS-II-026': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-027': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-028': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-029': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-030': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-031': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-032': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-033': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-034': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-035': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-036': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-037': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-038': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-039': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-040': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-041': { meter_type: 'EVC', units: 'CM' },
  'SMS-II-043': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-044': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-045': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-046': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-047': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-049': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-050': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-051': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-052': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-053': { meter_type: 'EVC', units: 'CM' },
  'SMS-II-054': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-055': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-056': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-057': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-058': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-059': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-060': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-061': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-062': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-063': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-064': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-065': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-066': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-067': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-068': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-069': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-070': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-072': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-073': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-074': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-075': { meter_type: 'EVC', units: 'CF' },
  'SMS-II-076': { meter_type: 'FC', units: 'MCF' },
  'SMS-II-077': { meter_type: 'EVC', units: 'CM' },
};

export const getMeterInfo = (
  clientId: string,
  overrides: Record<string, { meter_type?: string; units?: string }>
): MeterInfo => {
  const override = overrides[clientId];
  const defaults = DEFAULT_DEVICE_METERS[clientId];
  return {
    meter_type: override?.meter_type ?? defaults?.meter_type ?? '',
    units: override?.units ?? defaults?.units ?? '',
  };
};
